version: '1'

defaults:
  dockerfile: Dockerfile
  vars:
    configfile: config-rhel_centos

configurations:
  - name: fedora-26
    vars:
      base_img_reg: some.registry.fedoraproject.org
      base_img_name: fedora
      base_img_tag: 26
      configfile: config-fedora

  - name: some-special-rhel-7-name
    vars:
      base_img_reg: some.registry.redhat.com
      base_img_name: rhel
      base_img_tag: 7

  - name: centos-7
    vars:
      base_img_reg: some.registry.centos.org
      base_img_name: centos
      base_img_tag: 7
