version: '1'

defaults:
  files:
    # The help.md file is very similar for all combinations, so we provide just
    # one, but we want it rendered
    helpmd:
      path: help.md
  vars:
    # The configs for the service itself for rhel+centos vs fedora are very different,
    # therefore we provide different files
    configfile: config-rhel_centos
    distro_specific_help: |
      Some longer text for RHEL/CentOS goes here...

configurations:
  - name: fedora-26
    vars:
      base_img_reg: some.registry.fedoraproject.org
      base_img_name: fedora
      base_img_tag: 26
      configfile: config-fedora
      distro_specific_help: |
        These are Fedora-specific instructions

  - name: some-special-rhel-7-name
    vars:
      base_img_reg: some.registry.redhat.com
      base_img_name: rhel
      base_img_tag: 7

  - name: centos-7
    vars:
      base_img_reg: some.registry.centos.org
      base_img_name: centos
      base_img_tag: 7
